# Generated by Django 6.1 on 2026-08-29 01:37

import django.contrib.postgres.fields
import django.db.models.deletion
import users.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinic', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('dentist', 'Dentist'), ('receptionist', 'Receptionist'), ('assistant', 'Assistant'), ('accountant', 'Accountant')], db_index=True, max_length=15)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars/', validators=[users.validators.validate_image_size])),
                ('userPermissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=10)),
                ('workingDays', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]), default=list)),
                ('isActive', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_users', to='clinic.branch')),
                ('branches', models.ManyToManyField(db_index=True, related_name='related_users', to='clinic.branch')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
                'ordering': ['branch__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workingDays', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]), default=list)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('breakStart', models.TimeField(blank=True, null=True)),
                ('breakEnd', models.TimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_schedules', to='clinic.branch')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DoctorSchedules',
                'db_table': 'DoctorSchedules',
                'ordering': ['branch__name', 'doctor__name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('off', 'Off'), ('vacation', 'Vacation'), ('conference', 'Conference')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='users.doctorschedule')),
            ],
            options={
                'verbose_name_plural': 'DoctorScheduleExceptions',
                'db_table': 'DoctorScheduleExceptions',
            },
        ),
    ]
