# Generated by Django 6.0.5 on 2026-06-06 19:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('messageType', models.CharField(blank=True, choices=[('reminder', 'Reminder'), ('recall', 'Recall'), ('custom', 'Custom')], max_length=25, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='queued', max_length=25)),
                ('sentAt', models.DateTimeField(blank=True, null=True)),
                ('providerMessageId', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('templateLanguage', models.CharField(blank=True, max_length=20, null=True)),
                ('templateName', models.CharField(blank=True, max_length=255, null=True)),
                ('errorMessage', models.TextField(blank=True, null=True)),
                ('errorCode', models.CharField(blank=True, max_length=50, null=True)),
                ('lastWebhookAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_reminders', to='patients.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_reminders', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Messages',
                'db_table': 'Messages',
                'ordering': ['-sentAt'],
            },
        ),
    ]
