# Generated by Django 6.0.6 on 2026-06-30 17:54

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import patients.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(max_length=50, validators=[patients.validators.validate_phone_number])),
                ('workingDays', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]), default=list)),
                ('openTime', models.TimeField()),
                ('closeTime', models.TimeField()),
                ('isMain', models.BooleanField(default=False)),
                ('rooms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'Branches',
                'ordering': ['-isMain', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('routine_checkup', 'Routine Checkup'), ('cosmetic', 'Cosmetic'), ('diagnostic', 'Diagnostic'), ('endodontic', 'Endodontic'), ('implant', 'Implant'), ('preventive', 'Preventive'), ('prosthetic', 'Prosthetic'), ('restorative', 'Restorative'), ('surgical', 'Surgical')], max_length=25)),
                ('duration', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Procedures',
                'db_table': 'Procedures',
                'ordering': ['branch__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SterilizationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=255, null=True)),
                ('cycleType', models.CharField(choices=[('pre_vacuum', 'Pre-vacuum'), ('gravity', 'Gravity'), ('flash_immediate', 'Flash/Immediate'), ('chemical_vapor', 'Chemical Vapor'), ('dry_heat', 'Dry Heat')], max_length=50)),
                ('instrumentSets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('basic_exam_kit', 'Basic Exam Kit'), ('extraction_kit', 'Extraction Kit'), ('rct_kit', 'RCT Kit'), ('implant_kit', 'Implant Kit'), ('perio_kit', 'Perio Kit'), ('ortho_kit', 'Ortho Kit'), ('surgical_kit', 'Surgical Kit'), ('handpieces', 'Handpieces'), ('impression_trays', 'Impression Trays'), ('other', 'Other')], max_length=50), default=list)),
                ('result', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=50, null=True)),
                ('sealedAt', models.DateField(blank=True, null=True)),
                ('shelfLifeDays', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'SterilizationLogs',
                'db_table': 'SterilizationLogs',
                'ordering': ['branch__name', '-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='WaitingRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('in_chair', 'In chair'), ('done', 'Done')], max_length=25, null=True)),
                ('arrivedAt', models.DateTimeField(blank=True, null=True)),
                ('startedAt', models.DateTimeField(blank=True, null=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'WaitingRoom',
                'db_table': 'WaitingRoom',
                'ordering': ['-arrivedAt'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('currentStock', models.IntegerField()),
                ('minStock', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('lastOrdered', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_inventory', to='clinic.branch')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'db_table': 'Inventory',
                'ordering': ['branch__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50, validators=[patients.validators.validate_phone_number])),
                ('address', models.CharField(max_length=500)),
                ('contactPerson', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_labs', to='clinic.branch')),
            ],
            options={
                'verbose_name_plural': 'Labs',
                'db_table': 'Labs',
                'ordering': ['branch__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('toothNumber', models.CharField(max_length=3, validators=[patients.validators.validate_toothNumber])),
                ('instructions', models.CharField(blank=True, max_length=500, null=True)),
                ('sentDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('receivedDate', models.DateField(blank=True, null=True)),
                ('deliveredDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('sent', 'Sent'), ('in_production', 'In production'), ('delivered', 'Delivered'), ('received', 'Received')], max_length=20, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('labName', models.CharField(blank=True, max_length=255, null=True)),
                ('procedureName', models.CharField(blank=True, max_length=255, null=True)),
                ('patientName', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_lab_orders', to='clinic.branch')),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='clinic.lab')),
            ],
            options={
                'verbose_name_plural': 'LabOrders',
                'db_table': 'LabOrders',
                'ordering': ['branch__name', '-updatedAt'],
            },
        ),
    ]
