# Generated by Django 6.0.5 on 2026-06-19 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_lab_orders', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_procedures', to='clinic.branch'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_orders', to='clinic.procedure'),
        ),
        migrations.AddField(
            model_name='sterilizationlog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_sterilization_logs', to='clinic.branch'),
        ),
        migrations.AddField(
            model_name='waitingroom',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_rooms', to='patients.appointment'),
        ),
        migrations.AddField(
            model_name='waitingroom',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_rooms', to='clinic.branch'),
        ),
    ]
