# Generated by Django 6.0.5 on 2026-06-11 01:57

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import patients.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTaxConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clinicName', models.CharField(max_length=255)),
                ('taxId', models.CharField(blank=True, max_length=125, null=True)),
                ('activityCode', models.CharField(max_length=125)),
                ('commercialReg', models.CharField(max_length=125)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50, validators=[patients.validators.validate_phone_number])),
            ],
            options={
                'verbose_name_plural': 'ClinicalTaxConfigs',
                'db_table': 'ClinicalTaxConfigs',
                'ordering': ['clinicName'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('invoiceNumber', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10)),
                ('issuedAt', models.DateTimeField(blank=True, null=True)),
                ('submittedAt', models.DateTimeField(blank=True, null=True)),
                ('billDescription', models.CharField(blank=True, max_length=300, null=True)),
                ('patientName', models.CharField(blank=True, max_length=255, null=True)),
                ('branchName', models.CharField(blank=True, max_length=255, null=True)),
                ('treatmentTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Invoices',
                'db_table': 'Invoices',
                'ordering': ['branch__name', 'issuedAt', 'submittedAt', 'patient__name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxCode', models.CharField(blank=True, choices=[('D0120', 'D0120'), ('D0210', 'D0210'), ('D0330', 'D0330'), ('D1110', 'D1110'), ('D1120', 'D1120'), ('D2140', 'D2140'), ('D2390', 'D2390'), ('D2710', 'D2710'), ('D2750', 'D2750'), ('D2780', 'D2780'), ('D3310', 'D3310'), ('D3330', 'D3330'), ('D4341', 'D4341'), ('D5110', 'D5110'), ('D5120', 'D5120'), ('D6010', 'D6010'), ('D6065', 'D6065'), ('D7140', 'D7140'), ('D7210', 'D7210'), ('D8080', 'D8080'), ('D9930', 'D9930'), ('OTHER', 'OTHER')], max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('quantity', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name_plural': 'InvoiceItems',
                'db_table': 'InvoiceItems',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('insurance', 'Insurance'), ('mobile_wallet', 'Mobile wallet')], max_length=25, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('patientName', models.CharField(blank=True, max_length=255, null=True)),
                ('billDescription', models.CharField(blank=True, max_length=300, null=True)),
                ('branchName', models.CharField(blank=True, max_length=255, null=True)),
                ('treatmentTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'db_table': 'Transactions',
                'ordering': ['branch__name', '-date', 'patient__name'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('totalAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('totalPaid', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('branchName', models.CharField(blank=True, max_length=255, null=True)),
                ('patientName', models.CharField(blank=True, max_length=255, null=True)),
                ('treatmentTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('procedures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_bills', to='clinic.branch')),
            ],
            options={
                'verbose_name_plural': 'Bills',
                'db_table': 'Bills',
                'ordering': ['branch__name', '-updatedAt'],
            },
        ),
    ]
