# Generated by Django 6.0.5 on 2026-06-05 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0002_initial'),
        ('finances', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_bills', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='bill',
            name='treatment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_bills', to='patients.treatmentplan'),
        ),
        migrations.AddField(
            model_name='bill',
            name='visits',
            field=models.ManyToManyField(db_index=True, related_name='visit_bills', to='patients.visit'),
        ),
        migrations.AddField(
            model_name='clinicaltaxconfig',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_config', to='clinic.branch'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_invoice', to='finances.bill'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_invoices', to='clinic.branch'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_invoices', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='finances.invoice'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finances.bill'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_transactions', to='clinic.branch'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_transactions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_transactions', to='patients.visit'),
        ),
    ]
