# Generated by Django 6.0.5 on 2026-06-02 04:50

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import patients.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teeth', models.JSONField()),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'DentalChart',
                'db_table': 'DentalChart',
                'ordering': ['-lastUpdated'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('countryCode', models.CharField(max_length=6, validators=[patients.validators.validate_country_code])),
                ('phone', models.CharField(db_index=True, max_length=50, validators=[patients.validators.validate_phone_number])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nationalId', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('bloodType', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True)),
                ('allergies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True)),
                ('insurance', models.CharField(blank=True, max_length=255, null=True)),
                ('insuranceId', models.CharField(blank=True, max_length=120, null=True)),
                ('lastVisit', models.DateField(blank=True, null=True)),
                ('nextAppointment', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Patients',
                'db_table': 'Patients',
                'ordering': ['branch__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatientRecall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, validators=[patients.validators.validate_phone_number])),
                ('type', models.CharField(choices=[('checkup', 'Checkup'), ('post_procedure', 'Post-procedure'), ('treatment', 'Treatment'), ('custom', 'Custom')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('no_answer', 'No answer'), ('declined', 'Declined')], default='pending', max_length=50)),
                ('dueDate', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('contactedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'PatientRecalls',
                'db_table': 'PatientRecalls',
                'ordering': ['branch__name', 'patient__name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='active', max_length=50)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('paidAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('installmentMonths', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Full payment'), (3, '3 months'), (6, '6 months'), (12, '12 months')], null=True)),
                ('sessions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'TreatmentPlans',
                'db_table': 'TreatmentPlans',
                'ordering': ['-createdAt', 'patient__name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toothNumber', models.CharField(blank=True, max_length=3, null=True, validators=[patients.validators.validate_toothNumber])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('session', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in progress'), ('completed', 'completed')], default='pending', max_length=25)),
                ('notes', models.TextField(blank=True, null=True)),
                ('procedureName', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'TreatmentPlanItems',
                'db_table': 'TreatmentPlanItems',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('routine_checkup', 'Routine Checkup'), ('follow_up', 'Follow up'), ('emergency', 'Emergency')], max_length=50)),
                ('procedures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('xray', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Visits',
                'db_table': 'Visits',
                'ordering': ['-createdAt', 'patient__name'],
            },
        ),
        migrations.CreateModel(
            name='XRay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='xrays/', validators=[patients.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'XRays',
                'db_table': 'XRays',
                'ordering': ['-uploadedAt'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('routine_checkup', 'Routine Checkup'), ('follow_up', 'Follow up'), ('emergency', 'Emergency')], max_length=500)),
                ('room', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('completed', 'completed'), ('cancelled', 'cancelled')], db_index=True, default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('procedureName', models.CharField(blank=True, max_length=255, null=True)),
                ('doctorName', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_appointments', to='clinic.branch')),
            ],
            options={
                'verbose_name_plural': 'Appointments',
                'db_table': 'Appointments',
                'ordering': ['branch__name', '-createdAt', 'patient__name'],
            },
        ),
    ]
