# Generated by Django 6.0.6 on 2026-06-29 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0002_initial'),
        ('finances', '0002_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_appointments', to='clinic.procedure'),
        ),
        migrations.AddField(
            model_name='patient',
            name='branch',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_patients', to='clinic.branch'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dentalchart',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_dentalchart', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientcoverage',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_insurance', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientcoverage',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_coverages', to='finances.insuranceprovider'),
        ),
        migrations.AddField(
            model_name='patientrecall',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_patient_recalls', to='clinic.branch'),
        ),
        migrations.AddField(
            model_name='patientrecall',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_recalls', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_treatmentplans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_treatmentplans', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_items', to='clinic.procedure'),
        ),
        migrations.AddField(
            model_name='treatmentplanitem',
            name='treatmentPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_items', to='patients.treatmentplan'),
        ),
        migrations.AddField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_visits', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='xray',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_xrays', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['doctor'], name='patient_doctor_indx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['branch'], name='patient_branch_indx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['name'], name='patient_name_indx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['phone'], name='patient_phone_indx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['branch', 'name'], name='patient_name_branch_indx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['branch', 'date'], name='Appointment_branch__f041f1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'date', 'status'], name='Appointment_doctor__e817b1_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcoverage',
            index=models.Index(fields=['patient', 'provider'], name='PatientCove_patient_9ef9c4_idx'),
        ),
        migrations.AddIndex(
            model_name='patientrecall',
            index=models.Index(fields=['patient', 'branch'], name='PatientReca_patient_2c6860_idx'),
        ),
        migrations.AddIndex(
            model_name='patientrecall',
            index=models.Index(fields=['patient', 'branch', 'status'], name='PatientReca_patient_d60ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', 'date'], name='Visits_patient_aa596d_idx'),
        ),
    ]
